html:
    vnu: https://validator.w3.org/nu/
    include: ".dist/**/*.html"
    ignore: 
        - "./**/node_modules/**"
        - "./**/inc/**"
css:
    vnu: https://validator.w3.org/nu/
    include: "./dist/assets/css/**/*.css"
    ignore:
        - "./**/node_modules/**"